<?php
/** @var \BroCode\Maps\Block\MapWidget $block */
?>

<div id="mapid" class="u-brocode--map" style="height: 180px;"></div>

<script>
require(['jquery', 'leaflet', 'leaflet-markercluster'], function($) {
    var mymap = L.map('mapid').setView(
        [<?= $block->getMapCenterLat() ?>, <?= $block->getMapCenterLon() ?>],
        <?= $block->getMapZoom() ?>
    );
    L.tileLayer('<?= $block->getTileUrl() ?>', {
        attribution: '<?= $block->getTileAttribution() ?>'
    }).addTo(mymap);

    $.get('<?= $block->getMapsDataUrl() ?>').done(function(data) {
        var markers = L.markerClusterGroup();
        data.forEach(function(element) {
            var m = L.marker([element.lat, element.lon])
            .bindPopup(element.title)
            .openPopup();
            markers.addLayer(m);
        });
        mymap.addLayer(markers);
    });
})
</script>