<?php
/** @var \BroCode\Maps\Block\MapWidget $block */
?>

here comes the map integration

<div id="mapid" style="height: 180px;"></div>

<script>
require(['jquery', 'leaflet', 'leaflet-markercluster'], function($) {
    var mymap = L.map('mapid').setView(
        [<?= $block->getMapCenterLat() ?>, <?= $block->getMapCenterLon() ?>],
        <?= $block->getMapZoom() ?>
    );
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(mymap);

    $.get('<?= $block->getMapsDataUrl() ?>').done(function(data) {
        var markers = L.markerClusterGroup();
        data.forEach(function(element) {
            var m = L.marker([element.lat, element.lon])
            .bindPopup(element.title)
            .openPopup();
            markers.addLayer(m);
        });
        mymap.addLayer(markers);
    });
})
</script>